# Generated by Django 4.0.7 on 2022-08-03 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('pontos', models.IntegerField()),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='SobreviventeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(max_length=1)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('estaInfectado', models.BooleanField(default=False)),
                ('createAt', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sobrevivente',
            },
        ),
        migrations.CreateModel(
            name='InventarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zssnapi.itemmodel')),
                ('sobrevivente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zssnapi.sobreviventemodel')),
            ],
            options={
                'db_table': 'inventario',
            },
        ),
    ]
