# Generated by Django 4.0.7 on 2022-08-04 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zssnapi', '0002_sobreviventemodel_countalertinfected'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaminacaoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createAt', models.DateField(auto_now_add=True)),
                ('infectado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infectado', to='zssnapi.sobreviventemodel')),
                ('informante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informante', to='zssnapi.sobreviventemodel')),
            ],
            options={
                'db_table': 'contaminacao',
            },
        ),
    ]
