# Generated by Django 4.0.7 on 2022-08-05 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zssnapi', '0003_contaminacaomodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sobreviventemodel',
            name='createAt',
        ),
    ]
