# Generated by Django 4.0.7 on 2022-08-06 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zssnapi', '0006_alter_inventariomodel_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariomodel',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zssnapi.itemmodel'),
        ),
        migrations.AlterField(
            model_name='inventariomodel',
            name='sobrevivente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zssnapi.sobreviventemodel'),
        ),
    ]
