# Generated by Django 4.0.7 on 2022-08-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zssnapi', '0007_alter_inventariomodel_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobreviventemodel',
            name='itens',
            field=models.ManyToManyField(related_name='itens', through='zssnapi.InventarioModel', to='zssnapi.itemmodel'),
        ),
    ]
