# Generated by Django 4.0.7 on 2022-08-06 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zssnapi', '0008_sobreviventemodel_itens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sobreviventemodel',
            name='itens',
        ),
    ]
