# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "master" ]
env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  DB1_NAME: ${{ secrets.DB1_NAME }}
  DB1_USER: ${{ secrets.DB1_USER }}
  DB1_PASSWORD: ${{ secrets.DB1_PASSWORD }}
  DB1_HOST: ${{ secrets.DB1_HOST }}
  DB2_NAME: ${{ secrets.DB2_NAME }}
  DB2_USER: ${{ secrets.DB2_USER }}
  DB2_PASSWORD: ${{ secrets.DB2_PASSWORD }}
  DB2_HOST: ${{ secrets.DB2_HOST }}
  
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: |
        git fetch --all --unshallow
    - name: Set up Python 3.8.3
      uses: actions/setup-python@v3
      with:
        python-version: 3.8.3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with Django
      run: |
        python manage.py test --keepdb
    - name: Add remote origin
      if: github.ref == 'refs/heads/master' && job.status == 'success'
      run: |
        git remote add heroku https://heroku:${{ secrets.HEROKU_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
    - name: Deploy to Heroku
      run: |
        git push heroku HEAD:master -f
